### ISSUE TITLE
Bug with deconstruction of entities that cannot be deconstructed.

### ISSUE THREAD

**Issue by nirahiel** [Aidiakapi/early_construction#1]
I already posted that in the factorio mods page but I feel like you'll get a better attention to this one, since you wrote a notice about how we should post here.

-----------------

The early bots will sometimes try to deconstruct entities that can NOT be decontructed (for example, when you place a LTN station, two more entities come with it, one lamp and one combinator, these are not deconstructable but are still marked by the deconstruction tool), they'll fail, but then they'll immediately be destroyed.

(I'm filling so much bug reports, I feel like I should get an easter egg only for me in this mod XD)

**Comment by Aidiakapi** [comment]
Ahh right, I missed the notification of that on the mod portal. Thanks for posting it here though, this is a good place. I've been quite preoccupied the past few weeks, so things have been slow, but I should have more time from now on.

As for the issue itself, it's kind of a weird situation, since it might be closer to a bug in Factorio itself. Why are indestructible objects able to be marked for deconstruction. I'm going to do some experimentation, and see what the behaviors are, and see what I can do to fix things.

I very much appreciate all the bug reports, finding all these weird edge cases that are either hard to notice or only occur with other mods involved is great, otherwise they just wouldn't get solved.

Also, feel free to make an issue here to track progress on your feature suggestion (https://mods.factorio.com/mod/early_construction/discussion/5ce86702c8170c000dfbcbb1).

**Comment by Aidiakapi** [comment]
I couldn't find a way to mark non-minable entities for deconstruction without first setting them to minable, and then changing them back to non-minable.

Regardless, it should work just fine now, and the robots will just hover over it, until it becomes minable, or the deconstruction request is cancelled :).

**Comment by nirahiel** [comment]
How about an easter egg for me ? Can I request a slightly WTF feature to be added ? (And eventually have it active only for me, or have it more effects when I'm using it ? :3 )

**Comment by Aidiakapi** [comment]
Feel free to post any feature request. Whether I'll add it will depend on many factors though :P.
