### ISSUE TITLE
Suggestion : Make early bots usable in a roboport.

### ISSUE THREAD

**Issue by nirahiel** [Aidiakapi/early_construction#2]
I tried it, just to see, put an item on the ground, order it to be deconstructed, and put some early bots in a roboport. As expected it didn't work, but I hoped it would.
What happened : robot left roboport, picked up the item, and immediately disappeared (along with my item).
What I expected : robot leave roboport, pick up the item, does whatever it has to do with it (put it in chest, build something with it ...) then disappear.

**Comment by Aidiakapi** [comment]
This is now implemented by default. There is one minor quirk with the non-personal roboports (because they behave slightly differently from personal roboports), and that's that when they have placed or mined an item **while** also carrying repair packs, they will return the repair packs to the roboport, but then not self-destruct. So in this very rare scenario, you basically get some free early construction robots.

Other than that, I've completely rewritten the logic for how the destruction and such, which ensures that they'll never destroy any items. In addition to that, they can now be mined by hand, and if they never placed or mined anything, you'll get both the robot and whatever it was carrying. If they however placed or mined anything, they'll destroy the moment you pick them up.
